server:
  port: 8080
  
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      routes:
        - id: ms-mcsimulation
          uri: lb://ms-mcsimulation
          predicates:
            - Path=/mcsimulation/**
        - id: ms-userregister
          uri: lb://ms-userregister
          predicates:
            - Path=/userregister/**
        - id: ms-mcapplication
          uri: lb://ms-mcapplication
          predicates:
            - Path=/mcapplication/**
        - id: ms-mcevaluation
          uri: lb://ms-mcevaluation
          predicates:
            - Path=/mcevaluation/**
        - id: ms-mctracking
          uri: lb://ms-mctracking
          predicates:
            - Path=/mctracking/**
        - id: ms-totalcosts
          uri: lb://ms-totalcosts
          predicates:
            - Path=/totalcosts/**