apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-mcapplication-deployment
  labels:
    app: ms-mcapplication-deployment
spec:
  selector:
    matchLabels:
      app: ms-mcapplication-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-mcapplication-deployment
    spec:
      containers:
        - name: ms-mcapplication
          image: saki2002/ms-mcapplication
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "0"
            - name: CONFIG_SERVER_URI
              value: http://config-server-service:8888
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_MCAPPLICATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_MCAPPLICATION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_MCAPPLICATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_MCAPPLICATION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_MCAPPLICATION
---
apiVersion: v1
kind: Service
metadata:
  name: ms-mcapplication-service
  labels:
    app: ms-mcapplication-service
spec:
  selector:
    app: ms-mcapplication-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer