apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-mcsimulation-deployment
  labels:
    app: ms-mcsimulation-deployment
spec:
  selector:
    matchLabels:
      app: ms-mcsimulation-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-mcsimulation-deployment
    spec:
      containers:
        - name: ms-mcsimulation
          image: saki2002/ms-mcsimulation
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "0"
            - name: CONFIG_SERVER_URI
              value: http://config-server-service:8888
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_MCSIMULATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_MCSIMULATION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_MCSIMULATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_MCSIMULATION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_MCSIMULATION
---
apiVersion: v1
kind: Service
metadata:
  name: ms-mcsimulation-service
  labels:
    app: ms-mcsimulation-service
spec:
  selector:
    app: ms-mcsimulation-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer