apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-userregister-deployment
  labels:
    app: ms-userregister-deployment
spec:
  selector:
    matchLabels:
      app: ms-userregister-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-userregister-deployment
    spec:
      containers:
        - name: ms-userregister
          image: saki2002/ms-userregister
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "0"
            - name: CONFIG_SERVER_URI
              value: http://config-server-service:8888
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_USERREGISTER
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_USERREGISTER
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_USERREGISTER
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_USERREGISTER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_USERREGISTER
---
apiVersion: v1
kind: Service
metadata:
  name: ms-userregister-service
  labels:
    app: ms-userregister-service
spec:
  selector:
    app: ms-userregister-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer